image: node:latest

stages:
  - install
  - build
  - test
  - deploy

install:
  stage: install
  script: yarn

build:
  stage: build
  script: yarn build

test:
  stage: test
  script: yarn test

deploy:
  stage: deploy
  script: yarn deploy
  only:
    - master
